#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Using redis host $TEST_REDIS_HOST"

export TEST_REDIS_HOST

cd $SCRIPT_DIR
mkdir -p ../../output/tap/redis-lua
rm -f luacov.*
busted -c --output=TAP . >  ../../output/tap/redis-lua/busted.tap
cat luacov.report.out
