FROM node:4
RUN npm install -g node-gyp
RUN apt-get install comerr-dev

RUN mkdir /src

WORKDIR /src
COPY package.json package.json
COPY npm-shrinkwrap.json npm-shrinkwrap.json
COPY modules/ modules/
COPY shared/ shared/

RUN sed 's#http://beta-internal:4873/#http://10.0.0.140:4873/#g' -ibak npm-shrinkwrap.json
RUN npm install --registry http://10.0.0.140:4873/

COPY . .
# Horrible hack for now
CMD ["node", "web"]
