#!/bin/bash -eu

function join { local IFS="$1"; shift; echo "$*"; }

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

WORKSPACE=${WORKSPACE-$SCRIPT_DIR}
DEBUG=${DEBUG-}
NODE_VERSION=$(node --version)
NODE_VERSION=${NODE_VERSION#v} # Drop the `v` prefix

export WORKSPACE
export DEBUG
export NODE_VERSION

SU_TO_UID=${UID}
SU_TO_USER=${USER}
export SU_TO_USER
export SU_TO_UID


case $OSTYPE in
  darwin*)
    TARGET_DOCKER_CONTAINER=internal-mac
    mkdir -p "${SCRIPT_DIR}/node_modules_linux"
  ;;
  *)
    TARGET_DOCKER_CONTAINER=internal-min
    ;;
esac


ISOLATED_UNIQ_ID=${BUILD_NUMBER:-$(date +"%Y-%m-%dT%H:%M:%S")}

function finish {
  docker-compose -p "webapp-${ISOLATED_UNIQ_ID}" -f docker-compose.internal.yml stop
  docker-compose -p "webapp-${ISOLATED_UNIQ_ID}" -f docker-compose.internal.yml rm -f -v
}
trap finish EXIT

docker-compose -p "webapp-${ISOLATED_UNIQ_ID}" -f docker-compose.internal.yml run --rm mongosetup
docker-compose -p "webapp-${ISOLATED_UNIQ_ID}" -f docker-compose.internal.yml run \
    --rm --entrypoint "${WORKSPACE}/scripts/docker/exec/exec.sh $(join ' ' "$@")" \
    "${TARGET_DOCKER_CONTAINER}"

echo "exec-in-docker complete, shutting down"
