#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function startRedis {
  cp ./config/sentinel.dev.conf.template ./config/sentinel.dev.conf

  redis-server --loglevel warning --port 6379 --bind 127.0.0.1 &
  redis-server --loglevel warning --port 6380 --slaveof 127.0.0.1 6379 --bind 127.0.0.1 &
  redis-server ./config/sentinel.dev.conf --sentinel --bind 127.0.0.1 &
}

function startMongo {
  rm -f /usr/local/var/log/mongodb/mongo.log

  ulimit -n 1000
  mkdir -p /usr/local/var/mongodb/r0
  mkdir -p /usr/local/var/mongodb/r1

  mongod run \
    --config "$SCRIPT_DIR/config/mongo-server.one.yml" \
    --profile=1 \
    --slowms=15 &

  mongod run \
    --config "$SCRIPT_DIR/config/mongo-server.two.yml" \
    --profile=1 \
    --slowms=15 &

  while [[ "$(mongo --quiet --eval 'db.serverStatus().ok') || echo 0" = "0" ]]; do
    echo Waiting for replicaset to come online
    sleep 1
  done

  if [ "$(mongo --quiet --eval 'rs.status().ok')" -eq "0" ]; then
  	echo Replicaset not initialised. Initialising
  	./scripts/mongo/init-dev-mongo.sh

  	while [[ "$(mongo --quiet --eval 'rs.status().ok')" = "0" ]]; do
  		echo Waiting for replicaset to come online
  		mongo --eval 'printjson(rs.status())';
  		sleep 1
  	done

  	./scripts/upgrade-data.sh
  fi
}

function setupHostAlias {
  HOSTNAME=$1
  IP=$2
  CURRENT_ALIAS=$(grep " $HOSTNAME *$" /etc/hosts|sed 's/ .*//')
  if [[ "$CURRENT_ALIAS" != "$IP" ]]; then
    >&2 echo "Warning. Your current $HOSTNAME ($CURRENT_ALIAS) hostname does not match the IP $IP"
    read -p "Would you like to update your hostfile? Requires sudo [yN] " -r
    echo
    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
      if [[ -z "$CURRENT_ALIAS" ]]; then
        sudo /bin/sh -c "echo \"$IP $HOSTNAME\" >> /etc/hosts"
      else
        sudo /bin/sh -c "sed -i.bak \"s/.* $HOSTNAME */$IP $HOSTNAME/\" /etc/hosts"
      fi
    else
      echo Remember to add \'"$IP" "$HOSTNAME"\' to your /etc/hosts file
    fi

  fi
}

setupHostAlias gitter-mongo-dev 127.0.0.1
setupHostAlias gitter-redis-dev 127.0.0.1

(startRedis 1>&2 > /dev/null) &
(startMongo 1>&2 > /dev/null) &
