#!/bin/bash

set -euo pipefail
set -x

curl -q --fail -vi -XPOST "$ES_URL/_aliases?pretty=true" -d @- << EOD
{
  "actions": [{
    "add": {
      "index": "$INDEX_NAME",
      "alias": "gitter-primary"
    }
  }]
}
EOD
