#!/bin/bash -xe

set -x
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# source $SCRIPT_DIR/vars

curl --fail -vi -XPUT "$ES_URL/_river/$USER_RIVER/_meta?pretty=true" -d @- << EOD
{
  "type": "mongodb",
  "mongodb": {
    "servers": [
      { "host": "$MONGO_HOST_1", "port": $MONGO_PORT_1 },
      { "host": "$MONGO_HOST_2", "port": $MONGO_PORT_2 }
    ],
    "options": { },
    "db": "gitter",
    "collection": "users",
    "scriptType": "groovy",
    "script": "$($SCRIPT_DIR/inline $SCRIPT_DIR/scripts/river/user.groovy)"
  },
  "index": {
    "name": "$INDEX_NAME",
    "type": "user"
  }
}
EOD

sleep 2

curl --fail -vi -XPUT "$ES_URL/_river/$CHAT_RIVER/_meta?pretty=true" -d @- << EOD
{
  "type": "mongodb",
  "mongodb": {
    "servers": [
      { "host": "$MONGO_HOST_1", "port": $MONGO_PORT_1 },
      { "host": "$MONGO_HOST_2", "port": $MONGO_PORT_2 }
    ],
    "options": { },
    "db": "gitter",
    "collection": "chatmessages",
    "scriptType": "groovy",
    "script": "$($SCRIPT_DIR/inline $SCRIPT_DIR/scripts/river/chat.groovy)"
  },
  "index": {
    "name": "$INDEX_NAME",
    "type": "chat"
  }
}
EOD

sleep 2

curl --fail -vi -XPUT "$ES_URL/_river/$ROOM_RIVER/_meta?pretty=true" -d @- << EOD
{
  "type": "mongodb",
  "mongodb": {
    "servers": [
      { "host": "$MONGO_HOST_1", "port": $MONGO_PORT_1 },
      { "host": "$MONGO_HOST_2", "port": $MONGO_PORT_2 }
    ],
    "options": { },
    "db": "gitter",
    "collection": "troupes",
    "scriptType": "groovy",
    "script": "$($SCRIPT_DIR/inline $SCRIPT_DIR/scripts/river/room.groovy)"
  },
  "index": {
    "name": "$INDEX_NAME",
    "type": "room"
  }
}
EOD
